(tool-bar-mode -1)
(setq markdown-command "pandoc -f markdown -t html -s --mathjax --highlight-style=pygments")
(setq inhibit-startup-screen t)
(setq inhibit-startup-message t) 
(setq initial-scratch-message nil)
(package-initialize)
(setq evil-want-C-i-jump nil)
(require 'evil)
(evil-mode 1)
(require 'org)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(setq org-log-done t)
